# Site settings
title: eDC
header-img: img/home-bg.jpg
email: contact@edcamity.com
description: "The essence of entrepreneurship"
baseurl: "/blog"
url: "http://edcamity.com"
twitter_username: edcamity
facebook_username:  edcamity

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
